#
# This compose file is ment for developers only.
#

name: icons-for-md-dev # Will be used for auto naming (network, volume names)
services:
  app:
    extends:
      file: compose.base.yaml
      service: app
    image: 192.168.84.20:8082/icons-for-md:dev-latest
    ports:
      - 8402:3000 # These ports are in format <host-port>:<container-port>